name: R CMD Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run R CMD check

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: 'rcmdcheck'

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '--no-manual --as-cran'
          error-on: 'error'
          check-dir: 'check'
